---
- name: Deleted Operation on EOS Interfaces
  hosts: eos
  gather_facts: no
  collections:
    - arista.eos
  tasks:
    - name: Delete the specified interface configuration
      arista.eos.eos_interfaces:
        config:
          - name: Ethernet1
        state: deleted
      register: result

    - name: Print result
      ansible.builtin.debug:
        var: result
