---
- name: Replaced Operation on Junos Interfaces
  hosts: junos
  gather_facts: no
  collections:
    - junipernetworks.junos
  tasks:
    - name: Replace the existing configuration with the provided configuration
      junos_interfaces:
        config:
          - name: ge-0/0/1
            description: Replaced Configuration by Ansible - Interface 1
            mtu: 9000
            speed: 1g
            enabled: true
            duplex: full-duplex
            hold_time:
              up: 1000
              down: 1200
        state: replaced
      register: result

    - name: Print result
      debug:
        var: result
