---
- name: Gathered Operation on EOS Layer 2 Interfaces
  hosts: eos
  gather_facts: no
  collections:
    - arista.eos
  tasks:
    - name: Gather current interface configuration
      register: current_l2_interfaces
      arista.eos.eos_l2_interfaces:
        state: gathered

    - name: Print gathered configuration
      ansible.builtin.debug:
        var: current_l2_interfaces
