---
- name: Rendered Operation on EOS Layer 2 Interfaces
  hosts: eos
  gather_facts: no
  collections:
    - arista.eos
  tasks:
    - name: Render configuration template
      register: rendered_config
      arista.eos.eos_l2_interfaces:
        running_config: "{{ lookup('template', 'interface.j2') }}"
        state: rendered

    - name: Print rendered configuration
      ansible.builtin.debug:
        var: rendered_config
