---
- name: Replaced Operation on EOS Layer 2 Interfaces
  hosts: eos
  gather_facts: no
  collections:
    - arista.eos
  tasks:
    - name: Set config
      ansible.builtin.set_fact:
      config:
      - name: Ethernet1
        trunk:
          native_vlan: 20
          trunk_allowed_vlans:
            - 5-10
            - "15"
    
    - name: Replace device configuration with provided configuration
      register: result
      arista.eos.eos_l2_interfaces:
        config: "{{ config }}"
        state: replaced
      become: yes

    - name: Print result
      ansible.builtin.debug:
        var: result
