---
- name: Merged Operation on Junos l3_interfaces
  hosts: junos
  gather_facts: false
  collections:
    - junipernetworks.junos
  tasks:
    - name: Merge the provided configuration with the existing running configuration
      register: result
      junipernetworks.junos.junos_l3_interfaces: &id001
        config:
          - ipv4:
              - address: 10.10.10.22/31
              - address: 10.10.10.20/31
            mtu: 1450
            name: ge-0/0/0
            unit: '100'
          - ipv4:
              - address: 10.10.10.21/31
            ipv6:
              - address: 2001:db8::22/64
            mtu: 1350
            name: ge-0/0/0
            unit: '200'
          - name: ae0
            unit: '0'
          - ipv4:
              - address: 198.108.6.100/25
            name: fxp0
            unit: '0'
          - name: lo0
            unit: '0'
        state: merged

    - name: Print Result
      ansible.builtin.debug:
        var: result
